### ISSUE TITLE
Implementing backbone filter plugin architecture

### ISSUE THREAD

**Issue by ajasja** [ajasja/prosculpt#26]
This issue covers how prosculpt backbone level filter could/should be implemented.

The idea is that this plugins would be scripts (pyrosetta, pymol etc...) that would run on backbone after the RFDiffusion step.
These are usually very project specific an would best be implemented as plugins.
The script would be passed a pdb path and would return true for pass and false for fail. This could save significant computational time.

The plugin architecture would use [importlib](https://stackoverflow.com/a/41595552) to load the script. The plugins must have a method called 
`filter_backbone(pdb : str | Parh, kwargs: dict)` that returns either true or falls.

In the Yaml file there would be a new config 
```yaml
rfdiff_backbone_filters:
  - filter_name: num_neighbors
    filter_script: /path/to/script.py
    # if true the failed dirs get deleted
    delete_failed: true
    # Everything below get's passed to kwargs when calling filter backbone. Actually the whole dict can be passed.
    min_num_neighbors: 7
    max_num_neighbors: 50


  - filter_name: rollers assembly...
```

For now all the code to handle plugins should go into `plugin.py` in the main dir (we will make proscultp a true package in the future).
The example plugins (for example the num neighbors) should go into plugins subdir.

Here are the concrete steps:

1) Check that all the paths to plugin files exist and load them. Fail fast if this is not the case.
This function `load plugins` should be called here somewhere: https://github.com/ajasja/prosculpt/blob/5a858234f25b88a82e4aa1ba71ccc73100c1bc5f/rfdiff_mpnn_af2_merged.py#L542
Or maybe in or after `general_config_prep`

2)  A function called `filter_backbones_after_rfdiff(cfg.rfdiff_out_dir)` should be called here: https://github.com/ajasja/prosculpt/blob/5a858234f25b88a82e4aa1ba71ccc73100c1bc5f/rfdiff_mpnn_af2_merged.py#L567 after rfdiff finished

This should go through all the PDBs in that directory and for each pdb call all the defined plugins in a loop. If it gets a false value then that pdb should either be moved to a subfolder `failed_filters` or deleted dpending on the setting. 

Optionally the plugin could make `_XX.json` file with all the values that were calculated in the filter. 

**Will this work with the restart functionality?**
I think the missing pdb files will be generated on restart, but that is not a big problem.

Open Questions:
Should filters return values as well? Or at least save them to JSON os score file?
Should the name of the filter be fixed, or could you specify it with `my_pligin.py:main_method`?
Should we have an option that would keep caling rfdiff until the filters pass?
